"""empty message

Revision ID: 257a510cfeb7
Revises: None
Create Date: 2014-09-28 00:08:13.192284

"""

# revision identifiers, used by Alembic.
revision = '257a510cfeb7'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cookies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_cookie', sa.Integer(), nullable=True),
    sa.Column('block_url0', sa.String(length=255), nullable=True),
    sa.Column('block_url1', sa.String(length=255), nullable=True),
    sa.Column('block_url2', sa.String(length=255), nullable=True),
    sa.Column('block_url3', sa.String(length=255), nullable=True),
    sa.Column('block_url4', sa.String(length=255), nullable=True),
    sa.Column('block_url5', sa.String(length=255), nullable=True),
    sa.Column('block_url6', sa.String(length=255), nullable=True),
    sa.Column('block_url7', sa.String(length=255), nullable=True),
    sa.Column('block_url8', sa.String(length=255), nullable=True),
    sa.Column('block_url9', sa.String(length=255), nullable=True),
    sa.Column('block_url10', sa.String(length=255), nullable=True),
    sa.Column('block_url11', sa.String(length=255), nullable=True),
    sa.Column('block_url12', sa.String(length=255), nullable=True),
    sa.Column('block_url13', sa.String(length=255), nullable=True),
    sa.Column('block_url14', sa.String(length=255), nullable=True),
    sa.Column('block_url15', sa.String(length=255), nullable=True),
    sa.Column('block_url16', sa.String(length=255), nullable=True),
    sa.Column('block_url17', sa.String(length=255), nullable=True),
    sa.Column('block_url18', sa.String(length=255), nullable=True),
    sa.Column('block_url19', sa.String(length=255), nullable=True),
    sa.Column('block_url20', sa.String(length=255), nullable=True),
    sa.Column('block_url21', sa.String(length=255), nullable=True),
    sa.Column('block_url22', sa.String(length=255), nullable=True),
    sa.Column('block_url23', sa.String(length=255), nullable=True),
    sa.Column('block_url24', sa.String(length=255), nullable=True),
    sa.Column('block_url_img0', sa.String(length=255), nullable=True),
    sa.Column('block_url_img1', sa.String(length=255), nullable=True),
    sa.Column('block_url_img2', sa.String(length=255), nullable=True),
    sa.Column('block_url_img3', sa.String(length=255), nullable=True),
    sa.Column('block_url_img4', sa.String(length=255), nullable=True),
    sa.Column('block_url_img5', sa.String(length=255), nullable=True),
    sa.Column('block_url_img6', sa.String(length=255), nullable=True),
    sa.Column('block_url_img7', sa.String(length=255), nullable=True),
    sa.Column('block_url_img8', sa.String(length=255), nullable=True),
    sa.Column('block_url_img9', sa.String(length=255), nullable=True),
    sa.Column('block_url_img10', sa.String(length=255), nullable=True),
    sa.Column('block_url_img11', sa.String(length=255), nullable=True),
    sa.Column('block_url_img12', sa.String(length=255), nullable=True),
    sa.Column('block_url_img13', sa.String(length=255), nullable=True),
    sa.Column('block_url_img14', sa.String(length=255), nullable=True),
    sa.Column('block_url_img15', sa.String(length=255), nullable=True),
    sa.Column('block_url_img16', sa.String(length=255), nullable=True),
    sa.Column('block_url_img17', sa.String(length=255), nullable=True),
    sa.Column('block_url_img18', sa.String(length=255), nullable=True),
    sa.Column('block_url_img19', sa.String(length=255), nullable=True),
    sa.Column('block_url_img20', sa.String(length=255), nullable=True),
    sa.Column('block_url_img21', sa.String(length=255), nullable=True),
    sa.Column('block_url_img22', sa.String(length=255), nullable=True),
    sa.Column('block_url_img23', sa.String(length=255), nullable=True),
    sa.Column('block_url_img24', sa.String(length=255), nullable=True),
    sa.Column('block_widget0', sa.String(length=255), nullable=True),
    sa.Column('block_widget1', sa.String(length=255), nullable=True),
    sa.Column('block_widget2', sa.String(length=255), nullable=True),
    sa.Column('block_widget3', sa.String(length=255), nullable=True),
    sa.Column('block_widget4', sa.String(length=255), nullable=True),
    sa.Column('block_widget5', sa.String(length=255), nullable=True),
    sa.Column('block_widget6', sa.String(length=255), nullable=True),
    sa.Column('block_widget7', sa.String(length=255), nullable=True),
    sa.Column('block_widget8', sa.String(length=255), nullable=True),
    sa.Column('block_widget9', sa.String(length=255), nullable=True),
    sa.Column('block_widget10', sa.String(length=255), nullable=True),
    sa.Column('block_widget11', sa.String(length=255), nullable=True),
    sa.Column('block_widget12', sa.String(length=255), nullable=True),
    sa.Column('block_widget13', sa.String(length=255), nullable=True),
    sa.Column('block_widget14', sa.String(length=255), nullable=True),
    sa.Column('block_widget15', sa.String(length=255), nullable=True),
    sa.Column('block_widget16', sa.String(length=255), nullable=True),
    sa.Column('block_widget17', sa.String(length=255), nullable=True),
    sa.Column('block_widget18', sa.String(length=255), nullable=True),
    sa.Column('block_widget19', sa.String(length=255), nullable=True),
    sa.Column('block_widget20', sa.String(length=255), nullable=True),
    sa.Column('block_widget21', sa.String(length=255), nullable=True),
    sa.Column('block_widget22', sa.String(length=255), nullable=True),
    sa.Column('block_widget23', sa.String(length=255), nullable=True),
    sa.Column('block_widget24', sa.String(length=255), nullable=True),
    sa.Column('division_col', sa.Integer(), nullable=True),
    sa.Column('division_row', sa.Integer(), nullable=True),
    sa.Column('search', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_cookie'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cookies')
    ### end Alembic commands ###
