"""empty message

Revision ID: 551ab03a0f99
Revises: 257a510cfeb7
Create Date: 2014-09-28 13:14:27.320237

"""

# revision identifiers, used by Alembic.
revision = '551ab03a0f99'
down_revision = '257a510cfeb7'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
